/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Bootcamp Treinos API
 * API para o bootcamp de treinos do FSC
 * OpenAPI spec version: 1.0.0
 */
import { customFetch } from "../../fetch";
export type GetHomeData200TodayWorkoutDayWeekDay =
  (typeof GetHomeData200TodayWorkoutDayWeekDay)[keyof typeof GetHomeData200TodayWorkoutDayWeekDay];

export const GetHomeData200TodayWorkoutDayWeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type GetHomeData200TodayWorkoutDaySessionStatus =
  (typeof GetHomeData200TodayWorkoutDaySessionStatus)[keyof typeof GetHomeData200TodayWorkoutDaySessionStatus];

export const GetHomeData200TodayWorkoutDaySessionStatus = {
  not_started: "not_started",
  in_progress: "in_progress",
  completed: "completed",
} as const;

export type GetHomeData200TodayWorkoutDay = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutPlanId: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  isRest: boolean;
  weekDay: GetHomeData200TodayWorkoutDayWeekDay;
  estimatedDurationInSeconds: number;
  coverImageUrl?: string;
  exercisesCount: number;
  sessionStatus: GetHomeData200TodayWorkoutDaySessionStatus;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  sessionId?: string;
};

export type GetHomeData200ConsistencyByDay = {
  [key: string]: {
    workoutDayCompleted: boolean;
    workoutDayStarted: boolean;
  };
};

export type GetHomeData200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  activeWorkoutPlanId?: string;
  todayWorkoutDay?: GetHomeData200TodayWorkoutDay;
  workoutStreak: number;
  consistencyByDay: GetHomeData200ConsistencyByDay;
};

export type GetHomeData401 = {
  error: string;
  code: string;
};

export type GetHomeData404 = {
  error: string;
  code: string;
};

export type GetHomeData500 = {
  error: string;
  code: string;
};

export type GetUserTrainData200 =
  | {
      userId: string;
      userName: string;
      weightInGrams: number;
      heightInCentimeters: number;
      age: number;
      /**
       * @minimum 0
       * @maximum 100
       */
      bodyFatPercentage: number;
      isTrainer: boolean;
      incomplete?: boolean;
    }
  | {
      isTrainer: boolean;
      incomplete: boolean;
    }
  | null;

export type GetUserTrainData401 = {
  error: string;
  code: string;
};

export type GetUserTrainData500 = {
  error: string;
  code: string;
};

export type UpsertUserTrainDataBody = {
  /** @minimum 0 */
  weightInGrams: number;
  /** @minimum 0 */
  heightInCentimeters: number;
  /** @minimum 0 */
  age: number;
  /**
   * @minimum 0
   * @maximum 100
   */
  bodyFatPercentage: number;
};

export type UpsertUserTrainData200 = {
  userId: string;
  weightInGrams: number;
  heightInCentimeters: number;
  age: number;
  bodyFatPercentage: number;
};

export type UpsertUserTrainData401 = {
  error: string;
  code: string;
};

export type UpsertUserTrainData500 = {
  error: string;
  code: string;
};

export type GetStatsParams = {
  /**
   * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$
   */
  from: string;
  /**
   * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$
   */
  to: string;
};

export type GetStats200ConsistencyByDay = {
  [key: string]: {
    workoutDayCompleted: boolean;
    workoutDayStarted: boolean;
  };
};

export type GetStats200 = {
  workoutStreak: number;
  consistencyByDay: GetStats200ConsistencyByDay;
  completedWorkoutsCount: number;
  conclusionRate: number;
  totalTimeInSeconds: number;
};

export type GetStats401 = {
  error: string;
  code: string;
};

export type GetStats404 = {
  error: string;
  code: string;
};

export type GetStats500 = {
  error: string;
  code: string;
};

export type ListWorkoutPlansParams = {
  active?: ListWorkoutPlansActive;
};

export type ListWorkoutPlansActive =
  (typeof ListWorkoutPlansActive)[keyof typeof ListWorkoutPlansActive];

export const ListWorkoutPlansActive = {
  true: "true",
  false: "false",
} as const;

export type ListWorkoutPlans200ItemWorkoutDaysItemWeekDay =
  (typeof ListWorkoutPlans200ItemWorkoutDaysItemWeekDay)[keyof typeof ListWorkoutPlans200ItemWorkoutDaysItemWeekDay];

export const ListWorkoutPlans200ItemWorkoutDaysItemWeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type ListWorkoutPlans200ItemWorkoutDaysItemExercisesItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  order: number;
  name: string;
  sets: number;
  reps: number;
  restTimeInSeconds: number;
  weightSuggestion?: string;
  notes?: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  exerciseId?: string;
};

export type ListWorkoutPlans200ItemWorkoutDaysItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  weekDay: ListWorkoutPlans200ItemWorkoutDaysItemWeekDay;
  isRest: boolean;
  estimatedDurationInSeconds: number;
  coverImageUrl?: string;
  exercises: ListWorkoutPlans200ItemWorkoutDaysItemExercisesItem[];
};

export type ListWorkoutPlans200Item = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  isActive: boolean;
  workoutDays: ListWorkoutPlans200ItemWorkoutDaysItem[];
};

export type ListWorkoutPlans401 = {
  error: string;
  code: string;
};

export type ListWorkoutPlans500 = {
  error: string;
  code: string;
};

export type CreateWorkoutPlanBodyWorkoutDaysItemWeekDay =
  (typeof CreateWorkoutPlanBodyWorkoutDaysItemWeekDay)[keyof typeof CreateWorkoutPlanBodyWorkoutDaysItemWeekDay];

export const CreateWorkoutPlanBodyWorkoutDaysItemWeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type CreateWorkoutPlanBodyWorkoutDaysItemExercisesItem = {
  /** @minimum 0 */
  order: number;
  /** @minLength 1 */
  name: string;
  /** @minimum 1 */
  sets: number;
  /** @minimum 1 */
  reps: number;
  /** @minimum 1 */
  restTimeInSeconds: number;
};

export type CreateWorkoutPlanBodyWorkoutDaysItem = {
  /** @minLength 1 */
  name: string;
  weekDay: CreateWorkoutPlanBodyWorkoutDaysItemWeekDay;
  isRest?: boolean;
  /** @minimum 1 */
  estimatedDurationInSeconds: number;
  coverImageUrl?: string;
  exercises: CreateWorkoutPlanBodyWorkoutDaysItemExercisesItem[];
};

export type CreateWorkoutPlanBody = {
  /** @minLength 1 */
  name: string;
  workoutDays: CreateWorkoutPlanBodyWorkoutDaysItem[];
};

export type CreateWorkoutPlan201WorkoutDaysItemWeekDay =
  (typeof CreateWorkoutPlan201WorkoutDaysItemWeekDay)[keyof typeof CreateWorkoutPlan201WorkoutDaysItemWeekDay];

export const CreateWorkoutPlan201WorkoutDaysItemWeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type CreateWorkoutPlan201WorkoutDaysItemExercisesItem = {
  /** @minimum 0 */
  order: number;
  /** @minLength 1 */
  name: string;
  /** @minimum 1 */
  sets: number;
  /** @minimum 1 */
  reps: number;
  /** @minimum 1 */
  restTimeInSeconds: number;
};

export type CreateWorkoutPlan201WorkoutDaysItem = {
  /** @minLength 1 */
  name: string;
  weekDay: CreateWorkoutPlan201WorkoutDaysItemWeekDay;
  isRest: boolean;
  /** @minimum 1 */
  estimatedDurationInSeconds: number;
  coverImageUrl?: string;
  exercises: CreateWorkoutPlan201WorkoutDaysItemExercisesItem[];
};

export type CreateWorkoutPlan201 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @minLength 1 */
  name: string;
  workoutDays: CreateWorkoutPlan201WorkoutDaysItem[];
};

export type CreateWorkoutPlan400 = {
  error: string;
  code: string;
};

export type CreateWorkoutPlan401 = {
  error: string;
  code: string;
};

export type CreateWorkoutPlan404 = {
  error: string;
  code: string;
};

export type CreateWorkoutPlan500 = {
  error: string;
  code: string;
};

export type UpdateWorkoutPlanBodyWorkoutDaysItemWeekDay =
  (typeof UpdateWorkoutPlanBodyWorkoutDaysItemWeekDay)[keyof typeof UpdateWorkoutPlanBodyWorkoutDaysItemWeekDay];

export const UpdateWorkoutPlanBodyWorkoutDaysItemWeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type UpdateWorkoutPlanBodyWorkoutDaysItemExercisesItem = {
  /** @minimum 0 */
  order: number;
  /** @minLength 1 */
  name: string;
  /** @minimum 1 */
  sets: number;
  /** @minimum 1 */
  reps: number;
  /** @minimum 1 */
  restTimeInSeconds: number;
  weightSuggestion?: string;
  notes?: string;
  exerciseId?: string;
};

export type UpdateWorkoutPlanBodyWorkoutDaysItem = {
  weekDay: UpdateWorkoutPlanBodyWorkoutDaysItemWeekDay;
  name?: string;
  isRest?: boolean;
  estimatedDurationInSeconds?: number;
  coverImageUrl?: string;
  exercises?: UpdateWorkoutPlanBodyWorkoutDaysItemExercisesItem[];
};

export type UpdateWorkoutPlanBody = {
  /** @minLength 1 */
  name?: string;
  workoutDays?: UpdateWorkoutPlanBodyWorkoutDaysItem[];
};

export type UpdateWorkoutPlan200 = {
  id: string;
  name: string;
  workoutPlanUpdated: boolean;
};

export type UpdateWorkoutPlan401 = {
  error: string;
  code: string;
};

export type UpdateWorkoutPlan404 = {
  error: string;
  code: string;
};

export type UpdateWorkoutPlan500 = {
  error: string;
  code: string;
};

export type GetWorkoutPlan200WorkoutDaysItemWeekDay =
  (typeof GetWorkoutPlan200WorkoutDaysItemWeekDay)[keyof typeof GetWorkoutPlan200WorkoutDaysItemWeekDay];

export const GetWorkoutPlan200WorkoutDaysItemWeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type GetWorkoutPlan200WorkoutDaysItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  weekDay: GetWorkoutPlan200WorkoutDaysItemWeekDay;
  name: string;
  isRest: boolean;
  coverImageUrl?: string;
  estimatedDurationInSeconds: number;
  exercisesCount: number;
};

export type GetWorkoutPlan200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  workoutDays: GetWorkoutPlan200WorkoutDaysItem[];
};

export type GetWorkoutPlan401 = {
  error: string;
  code: string;
};

export type GetWorkoutPlan404 = {
  error: string;
  code: string;
};

export type GetWorkoutPlan500 = {
  error: string;
  code: string;
};

export type GetWorkoutDay200WeekDay =
  (typeof GetWorkoutDay200WeekDay)[keyof typeof GetWorkoutDay200WeekDay];

export const GetWorkoutDay200WeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type GetWorkoutDay200ExercisesItemLogsItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  setNumber: number;
  /** @nullable */
  weightInKg: number | null;
  repsCompleted: number;
};

export type GetWorkoutDay200ExercisesItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  order: number;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutDayId: string;
  sets: number;
  reps: number;
  restTimeInSeconds: number;
  weightSuggestion?: string;
  notes?: string;
  gifUrl?: string;
  exerciseId?: string;
  logs: GetWorkoutDay200ExercisesItemLogsItem[];
};

export type GetWorkoutDay200SessionsItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutDayId: string;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$ */
  startedAt?: string;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$ */
  completedAt?: string;
};

export type GetWorkoutDay200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  isRest: boolean;
  coverImageUrl?: string;
  estimatedDurationInSeconds: number;
  weekDay: GetWorkoutDay200WeekDay;
  exercises: GetWorkoutDay200ExercisesItem[];
  sessions: GetWorkoutDay200SessionsItem[];
};

export type GetWorkoutDay401 = {
  error: string;
  code: string;
};

export type GetWorkoutDay404 = {
  error: string;
  code: string;
};

export type GetWorkoutDay500 = {
  error: string;
  code: string;
};

export type StartWorkoutSession201 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  userWorkoutSessionId: string;
};

export type StartWorkoutSession401 = {
  error: string;
  code: string;
};

export type StartWorkoutSession404 = {
  error: string;
  code: string;
};

export type StartWorkoutSession409 = {
  error: string;
  code: string;
};

export type StartWorkoutSession422 = {
  error: string;
  code: string;
};

export type StartWorkoutSession500 = {
  error: string;
  code: string;
};

export type UpdateWorkoutSessionBody = {
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  completedAt: string;
};

export type UpdateWorkoutSession200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  startedAt: string;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  completedAt: string;
};

export type UpdateWorkoutSession401 = {
  error: string;
  code: string;
};

export type UpdateWorkoutSession404 = {
  error: string;
  code: string;
};

export type UpdateWorkoutSession500 = {
  error: string;
  code: string;
};

export type LogExerciseSetBody = {
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  setNumber: number;
  /** @minimum 0 */
  weightInKg?: number;
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  repsCompleted: number;
};

export type LogExerciseSet201 = {
  id: string;
  workoutExerciseId: string;
  workoutSessionId: string;
  setNumber: number;
  /** @nullable */
  weightInKg: number | null;
  repsCompleted: number;
  createdAt: string;
};

export type LogExerciseSet401 = {
  error: string;
  code: string;
};

export type LogExerciseSet404 = {
  error: string;
  code: string;
};

export type LogExerciseSet500 = {
  error: string;
  code: string;
};

export type GetExerciseLogs200LogsItem = {
  id: string;
  setNumber: number;
  /** @nullable */
  weightInKg: number | null;
  repsCompleted: number;
  createdAt: string;
};

export type GetExerciseLogs200 = {
  logs: GetExerciseLogs200LogsItem[];
};

export type GetExerciseLogs401 = {
  error: string;
  code: string;
};

export type GetExerciseLogs500 = {
  error: string;
  code: string;
};

export type PatchWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdExercisesReorderBodyExercisesItem =
  {
    id: string;
    order: number;
  };

export type PatchWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdExercisesReorderBody =
  {
    exercises: PatchWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdExercisesReorderBodyExercisesItem[];
  };

export type PostAiBodyMessagesItemRole =
  (typeof PostAiBodyMessagesItemRole)[keyof typeof PostAiBodyMessagesItemRole];

export const PostAiBodyMessagesItemRole = {
  user: "user",
  assistant: "assistant",
  system: "system",
} as const;

export type PostAiBodyMessagesItem = {
  id: string;
  role: PostAiBodyMessagesItemRole;
  content?: string | unknown[];
  /** @maxItems 50 */
  parts: unknown[];
  createdAt?: unknown;
};

export type PostAiBody = {
  /** @maxItems 100 */
  messages: PostAiBodyMessagesItem[];
};

export type PostNutritionAiBodyMessagesItemRole =
  (typeof PostNutritionAiBodyMessagesItemRole)[keyof typeof PostNutritionAiBodyMessagesItemRole];

export const PostNutritionAiBodyMessagesItemRole = {
  user: "user",
  assistant: "assistant",
  system: "system",
} as const;

export type PostNutritionAiBodyMessagesItem = {
  id: string;
  role: PostNutritionAiBodyMessagesItemRole;
  content?: string | unknown[];
  /** @maxItems 50 */
  parts: unknown[];
  createdAt?: unknown;
};

export type PostNutritionAiBody = {
  /** @maxItems 100 */
  messages: PostNutritionAiBodyMessagesItem[];
};

export type GetExercisesParams = {
  muscles?: string;
};

export type GetExercises200Item = {
  id: string;
  /** @nullable */
  name: string | null;
  muscles: string[];
  /** @nullable */
  gifUrl: string | null;
};

export type GetExercisesId200 = {
  id: string;
  /** @nullable */
  name: string | null;
  muscles: string[];
  /** @nullable */
  gifUrl: string | null;
};

export type GetExercisesId404 = {
  error: string;
};

export type BecomeTrainerBody = {
  isTrainer: boolean;
};

export type BecomeTrainer200 = {
  isTrainer: boolean;
};

export type BecomeTrainer401 = {
  error: string;
  code: string;
};

export type BecomeTrainer500 = {
  error: string;
  code: string;
};

export type LinkTrainerBody = {
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  trainerEmail: string;
};

export type LinkTrainer200 = {
  id: string;
  status: string;
  trainerId: string;
  studentId: string;
};

export type LinkTrainer400 = {
  error: string;
  code: string;
};

export type LinkTrainer401 = {
  error: string;
  code: string;
};

export type LinkTrainer500 = {
  error: string;
  code: string;
};

export type GetMyStudents200ItemStudent = {
  id: string;
  name: string;
  email: string;
  /** @nullable */
  image: string | null;
};

export type GetMyStudents200Item = {
  id: string;
  status: string;
  createdAt: string;
  student: GetMyStudents200ItemStudent;
};

export type GetMyStudents401 = {
  error: string;
  code: string;
};

export type GetMyStudents500 = {
  error: string;
  code: string;
};

export type RespondStudentRequestBodyAction =
  (typeof RespondStudentRequestBodyAction)[keyof typeof RespondStudentRequestBodyAction];

export const RespondStudentRequestBodyAction = {
  accept: "accept",
  reject: "reject",
} as const;

export type RespondStudentRequestBody = {
  action: RespondStudentRequestBodyAction;
};

export type RespondStudentRequest200 = {
  status: string;
};

export type RespondStudentRequest401 = {
  error: string;
  code: string;
};

export type RespondStudentRequest404 = {
  error: string;
  code: string;
};

export type RespondStudentRequest500 = {
  error: string;
  code: string;
};

export type GetStudentPlans401 = {
  error: string;
  code: string;
};

export type GetStudentPlans404 = {
  error: string;
  code: string;
};

export type GetStudentPlans500 = {
  error: string;
  code: string;
};

export type Get200 = {
  message: string;
};

/**
 * @summary Get home page data
 */
export type getHomeDataResponse200 = {
  data: GetHomeData200;
  status: 200;
};

export type getHomeDataResponse401 = {
  data: GetHomeData401;
  status: 401;
};

export type getHomeDataResponse404 = {
  data: GetHomeData404;
  status: 404;
};

export type getHomeDataResponse500 = {
  data: GetHomeData500;
  status: 500;
};

export type getHomeDataResponseSuccess = getHomeDataResponse200 & {
  headers: Headers;
};
export type getHomeDataResponseError = (
  | getHomeDataResponse401
  | getHomeDataResponse404
  | getHomeDataResponse500
) & {
  headers: Headers;
};

export type getHomeDataResponse =
  | getHomeDataResponseSuccess
  | getHomeDataResponseError;

export const getGetHomeDataUrl = (date: string) => {
  return `/home/${date}`;
};

export const getHomeData = async (
  date: string,
  options?: RequestInit,
): Promise<getHomeDataResponse> => {
  return customFetch<getHomeDataResponse>(getGetHomeDataUrl(date), {
    ...options,
    method: "GET",
  });
};

/**
 * Get user train data
 * @summary Get user train data
 */
export type getUserTrainDataResponse200 = {
  data: GetUserTrainData200;
  status: 200;
};

export type getUserTrainDataResponse401 = {
  data: GetUserTrainData401;
  status: 401;
};

export type getUserTrainDataResponse500 = {
  data: GetUserTrainData500;
  status: 500;
};

export type getUserTrainDataResponseSuccess = getUserTrainDataResponse200 & {
  headers: Headers;
};
export type getUserTrainDataResponseError = (
  | getUserTrainDataResponse401
  | getUserTrainDataResponse500
) & {
  headers: Headers;
};

export type getUserTrainDataResponse =
  | getUserTrainDataResponseSuccess
  | getUserTrainDataResponseError;

export const getGetUserTrainDataUrl = () => {
  return `/me/`;
};

export const getUserTrainData = async (
  options?: RequestInit,
): Promise<getUserTrainDataResponse> => {
  return customFetch<getUserTrainDataResponse>(getGetUserTrainDataUrl(), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Upsert user train data
 */
export type upsertUserTrainDataResponse200 = {
  data: UpsertUserTrainData200;
  status: 200;
};

export type upsertUserTrainDataResponse401 = {
  data: UpsertUserTrainData401;
  status: 401;
};

export type upsertUserTrainDataResponse500 = {
  data: UpsertUserTrainData500;
  status: 500;
};

export type upsertUserTrainDataResponseSuccess =
  upsertUserTrainDataResponse200 & {
    headers: Headers;
  };
export type upsertUserTrainDataResponseError = (
  | upsertUserTrainDataResponse401
  | upsertUserTrainDataResponse500
) & {
  headers: Headers;
};

export type upsertUserTrainDataResponse =
  | upsertUserTrainDataResponseSuccess
  | upsertUserTrainDataResponseError;

export const getUpsertUserTrainDataUrl = () => {
  return `/me/`;
};

export const upsertUserTrainData = async (
  upsertUserTrainDataBody: UpsertUserTrainDataBody,
  options?: RequestInit,
): Promise<upsertUserTrainDataResponse> => {
  return customFetch<upsertUserTrainDataResponse>(getUpsertUserTrainDataUrl(), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(upsertUserTrainDataBody),
  });
};

/**
 * @summary Get user workout stats
 */
export type getStatsResponse200 = {
  data: GetStats200;
  status: 200;
};

export type getStatsResponse401 = {
  data: GetStats401;
  status: 401;
};

export type getStatsResponse404 = {
  data: GetStats404;
  status: 404;
};

export type getStatsResponse500 = {
  data: GetStats500;
  status: 500;
};

export type getStatsResponseSuccess = getStatsResponse200 & {
  headers: Headers;
};
export type getStatsResponseError = (
  | getStatsResponse401
  | getStatsResponse404
  | getStatsResponse500
) & {
  headers: Headers;
};

export type getStatsResponse = getStatsResponseSuccess | getStatsResponseError;

export const getGetStatsUrl = (params: GetStatsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/stats/?${stringifiedParams}`
    : `/stats/`;
};

export const getStats = async (
  params: GetStatsParams,
  options?: RequestInit,
): Promise<getStatsResponse> => {
  return customFetch<getStatsResponse>(getGetStatsUrl(params), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary List workout plans
 */
export type listWorkoutPlansResponse200 = {
  data: ListWorkoutPlans200Item[];
  status: 200;
};

export type listWorkoutPlansResponse401 = {
  data: ListWorkoutPlans401;
  status: 401;
};

export type listWorkoutPlansResponse500 = {
  data: ListWorkoutPlans500;
  status: 500;
};

export type listWorkoutPlansResponseSuccess = listWorkoutPlansResponse200 & {
  headers: Headers;
};
export type listWorkoutPlansResponseError = (
  | listWorkoutPlansResponse401
  | listWorkoutPlansResponse500
) & {
  headers: Headers;
};

export type listWorkoutPlansResponse =
  | listWorkoutPlansResponseSuccess
  | listWorkoutPlansResponseError;

export const getListWorkoutPlansUrl = (params?: ListWorkoutPlansParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/workout-plans/?${stringifiedParams}`
    : `/workout-plans/`;
};

export const listWorkoutPlans = async (
  params?: ListWorkoutPlansParams,
  options?: RequestInit,
): Promise<listWorkoutPlansResponse> => {
  return customFetch<listWorkoutPlansResponse>(getListWorkoutPlansUrl(params), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Create a workout plan
 */
export type createWorkoutPlanResponse201 = {
  data: CreateWorkoutPlan201;
  status: 201;
};

export type createWorkoutPlanResponse400 = {
  data: CreateWorkoutPlan400;
  status: 400;
};

export type createWorkoutPlanResponse401 = {
  data: CreateWorkoutPlan401;
  status: 401;
};

export type createWorkoutPlanResponse404 = {
  data: CreateWorkoutPlan404;
  status: 404;
};

export type createWorkoutPlanResponse500 = {
  data: CreateWorkoutPlan500;
  status: 500;
};

export type createWorkoutPlanResponseSuccess = createWorkoutPlanResponse201 & {
  headers: Headers;
};
export type createWorkoutPlanResponseError = (
  | createWorkoutPlanResponse400
  | createWorkoutPlanResponse401
  | createWorkoutPlanResponse404
  | createWorkoutPlanResponse500
) & {
  headers: Headers;
};

export type createWorkoutPlanResponse =
  | createWorkoutPlanResponseSuccess
  | createWorkoutPlanResponseError;

export const getCreateWorkoutPlanUrl = () => {
  return `/workout-plans/`;
};

export const createWorkoutPlan = async (
  createWorkoutPlanBody: CreateWorkoutPlanBody,
  options?: RequestInit,
): Promise<createWorkoutPlanResponse> => {
  return customFetch<createWorkoutPlanResponse>(getCreateWorkoutPlanUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createWorkoutPlanBody),
  });
};

/**
 * @summary Update a workout plan
 */
export type updateWorkoutPlanResponse200 = {
  data: UpdateWorkoutPlan200;
  status: 200;
};

export type updateWorkoutPlanResponse401 = {
  data: UpdateWorkoutPlan401;
  status: 401;
};

export type updateWorkoutPlanResponse404 = {
  data: UpdateWorkoutPlan404;
  status: 404;
};

export type updateWorkoutPlanResponse500 = {
  data: UpdateWorkoutPlan500;
  status: 500;
};

export type updateWorkoutPlanResponseSuccess = updateWorkoutPlanResponse200 & {
  headers: Headers;
};
export type updateWorkoutPlanResponseError = (
  | updateWorkoutPlanResponse401
  | updateWorkoutPlanResponse404
  | updateWorkoutPlanResponse500
) & {
  headers: Headers;
};

export type updateWorkoutPlanResponse =
  | updateWorkoutPlanResponseSuccess
  | updateWorkoutPlanResponseError;

export const getUpdateWorkoutPlanUrl = (workoutPlanId: string) => {
  return `/workout-plans/${workoutPlanId}`;
};

export const updateWorkoutPlan = async (
  workoutPlanId: string,
  updateWorkoutPlanBody: UpdateWorkoutPlanBody,
  options?: RequestInit,
): Promise<updateWorkoutPlanResponse> => {
  return customFetch<updateWorkoutPlanResponse>(
    getUpdateWorkoutPlanUrl(workoutPlanId),
    {
      ...options,
      method: "PATCH",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(updateWorkoutPlanBody),
    },
  );
};

/**
 * @summary Get a workout plan
 */
export type getWorkoutPlanResponse200 = {
  data: GetWorkoutPlan200;
  status: 200;
};

export type getWorkoutPlanResponse401 = {
  data: GetWorkoutPlan401;
  status: 401;
};

export type getWorkoutPlanResponse404 = {
  data: GetWorkoutPlan404;
  status: 404;
};

export type getWorkoutPlanResponse500 = {
  data: GetWorkoutPlan500;
  status: 500;
};

export type getWorkoutPlanResponseSuccess = getWorkoutPlanResponse200 & {
  headers: Headers;
};
export type getWorkoutPlanResponseError = (
  | getWorkoutPlanResponse401
  | getWorkoutPlanResponse404
  | getWorkoutPlanResponse500
) & {
  headers: Headers;
};

export type getWorkoutPlanResponse =
  | getWorkoutPlanResponseSuccess
  | getWorkoutPlanResponseError;

export const getGetWorkoutPlanUrl = (workoutPlanId: string) => {
  return `/workout-plans/${workoutPlanId}`;
};

export const getWorkoutPlan = async (
  workoutPlanId: string,
  options?: RequestInit,
): Promise<getWorkoutPlanResponse> => {
  return customFetch<getWorkoutPlanResponse>(
    getGetWorkoutPlanUrl(workoutPlanId),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Get a workout day
 */
export type getWorkoutDayResponse200 = {
  data: GetWorkoutDay200;
  status: 200;
};

export type getWorkoutDayResponse401 = {
  data: GetWorkoutDay401;
  status: 401;
};

export type getWorkoutDayResponse404 = {
  data: GetWorkoutDay404;
  status: 404;
};

export type getWorkoutDayResponse500 = {
  data: GetWorkoutDay500;
  status: 500;
};

export type getWorkoutDayResponseSuccess = getWorkoutDayResponse200 & {
  headers: Headers;
};
export type getWorkoutDayResponseError = (
  | getWorkoutDayResponse401
  | getWorkoutDayResponse404
  | getWorkoutDayResponse500
) & {
  headers: Headers;
};

export type getWorkoutDayResponse =
  | getWorkoutDayResponseSuccess
  | getWorkoutDayResponseError;

export const getGetWorkoutDayUrl = (
  workoutPlanId: string,
  workoutDayId: string,
) => {
  return `/workout-plans/${workoutPlanId}/days/${workoutDayId}`;
};

export const getWorkoutDay = async (
  workoutPlanId: string,
  workoutDayId: string,
  options?: RequestInit,
): Promise<getWorkoutDayResponse> => {
  return customFetch<getWorkoutDayResponse>(
    getGetWorkoutDayUrl(workoutPlanId, workoutDayId),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Start a workout session
 */
export type startWorkoutSessionResponse201 = {
  data: StartWorkoutSession201;
  status: 201;
};

export type startWorkoutSessionResponse401 = {
  data: StartWorkoutSession401;
  status: 401;
};

export type startWorkoutSessionResponse404 = {
  data: StartWorkoutSession404;
  status: 404;
};

export type startWorkoutSessionResponse409 = {
  data: StartWorkoutSession409;
  status: 409;
};

export type startWorkoutSessionResponse422 = {
  data: StartWorkoutSession422;
  status: 422;
};

export type startWorkoutSessionResponse500 = {
  data: StartWorkoutSession500;
  status: 500;
};

export type startWorkoutSessionResponseSuccess =
  startWorkoutSessionResponse201 & {
    headers: Headers;
  };
export type startWorkoutSessionResponseError = (
  | startWorkoutSessionResponse401
  | startWorkoutSessionResponse404
  | startWorkoutSessionResponse409
  | startWorkoutSessionResponse422
  | startWorkoutSessionResponse500
) & {
  headers: Headers;
};

export type startWorkoutSessionResponse =
  | startWorkoutSessionResponseSuccess
  | startWorkoutSessionResponseError;

export const getStartWorkoutSessionUrl = (
  workoutPlanId: string,
  workoutDayId: string,
) => {
  return `/workout-plans/${workoutPlanId}/days/${workoutDayId}/sessions`;
};

export const startWorkoutSession = async (
  workoutPlanId: string,
  workoutDayId: string,
  options?: RequestInit,
): Promise<startWorkoutSessionResponse> => {
  return customFetch<startWorkoutSessionResponse>(
    getStartWorkoutSessionUrl(workoutPlanId, workoutDayId),
    {
      ...options,
      method: "POST",
    },
  );
};

/**
 * @summary Update a workout session
 */
export type updateWorkoutSessionResponse200 = {
  data: UpdateWorkoutSession200;
  status: 200;
};

export type updateWorkoutSessionResponse401 = {
  data: UpdateWorkoutSession401;
  status: 401;
};

export type updateWorkoutSessionResponse404 = {
  data: UpdateWorkoutSession404;
  status: 404;
};

export type updateWorkoutSessionResponse500 = {
  data: UpdateWorkoutSession500;
  status: 500;
};

export type updateWorkoutSessionResponseSuccess =
  updateWorkoutSessionResponse200 & {
    headers: Headers;
  };
export type updateWorkoutSessionResponseError = (
  | updateWorkoutSessionResponse401
  | updateWorkoutSessionResponse404
  | updateWorkoutSessionResponse500
) & {
  headers: Headers;
};

export type updateWorkoutSessionResponse =
  | updateWorkoutSessionResponseSuccess
  | updateWorkoutSessionResponseError;

export const getUpdateWorkoutSessionUrl = (
  workoutPlanId: string,
  workoutDayId: string,
  sessionId: string,
) => {
  return `/workout-plans/${workoutPlanId}/days/${workoutDayId}/sessions/${sessionId}`;
};

export const updateWorkoutSession = async (
  workoutPlanId: string,
  workoutDayId: string,
  sessionId: string,
  updateWorkoutSessionBody: UpdateWorkoutSessionBody,
  options?: RequestInit,
): Promise<updateWorkoutSessionResponse> => {
  return customFetch<updateWorkoutSessionResponse>(
    getUpdateWorkoutSessionUrl(workoutPlanId, workoutDayId, sessionId),
    {
      ...options,
      method: "PATCH",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(updateWorkoutSessionBody),
    },
  );
};

/**
 * @summary Log an exercise set
 */
export type logExerciseSetResponse201 = {
  data: LogExerciseSet201;
  status: 201;
};

export type logExerciseSetResponse401 = {
  data: LogExerciseSet401;
  status: 401;
};

export type logExerciseSetResponse404 = {
  data: LogExerciseSet404;
  status: 404;
};

export type logExerciseSetResponse500 = {
  data: LogExerciseSet500;
  status: 500;
};

export type logExerciseSetResponseSuccess = logExerciseSetResponse201 & {
  headers: Headers;
};
export type logExerciseSetResponseError = (
  | logExerciseSetResponse401
  | logExerciseSetResponse404
  | logExerciseSetResponse500
) & {
  headers: Headers;
};

export type logExerciseSetResponse =
  | logExerciseSetResponseSuccess
  | logExerciseSetResponseError;

export const getLogExerciseSetUrl = (
  workoutPlanId: string,
  workoutDayId: string,
  sessionId: string,
  exerciseId: string,
) => {
  return `/workout-plans/${workoutPlanId}/days/${workoutDayId}/sessions/${sessionId}/exercises/${exerciseId}/logs`;
};

export const logExerciseSet = async (
  workoutPlanId: string,
  workoutDayId: string,
  sessionId: string,
  exerciseId: string,
  logExerciseSetBody: LogExerciseSetBody,
  options?: RequestInit,
): Promise<logExerciseSetResponse> => {
  return customFetch<logExerciseSetResponse>(
    getLogExerciseSetUrl(workoutPlanId, workoutDayId, sessionId, exerciseId),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(logExerciseSetBody),
    },
  );
};

/**
 * @summary Get exercise logs
 */
export type getExerciseLogsResponse200 = {
  data: GetExerciseLogs200;
  status: 200;
};

export type getExerciseLogsResponse401 = {
  data: GetExerciseLogs401;
  status: 401;
};

export type getExerciseLogsResponse500 = {
  data: GetExerciseLogs500;
  status: 500;
};

export type getExerciseLogsResponseSuccess = getExerciseLogsResponse200 & {
  headers: Headers;
};
export type getExerciseLogsResponseError = (
  | getExerciseLogsResponse401
  | getExerciseLogsResponse500
) & {
  headers: Headers;
};

export type getExerciseLogsResponse =
  | getExerciseLogsResponseSuccess
  | getExerciseLogsResponseError;

export const getGetExerciseLogsUrl = (
  workoutPlanId: string,
  workoutDayId: string,
  exerciseId: string,
) => {
  return `/workout-plans/${workoutPlanId}/days/${workoutDayId}/exercises/${exerciseId}/logs`;
};

export const getExerciseLogs = async (
  workoutPlanId: string,
  workoutDayId: string,
  exerciseId: string,
  options?: RequestInit,
): Promise<getExerciseLogsResponse> => {
  return customFetch<getExerciseLogsResponse>(
    getGetExerciseLogsUrl(workoutPlanId, workoutDayId, exerciseId),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Reorder exercises
 */
export type patchWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdExercisesReorderResponse200 =
  {
    data: void;
    status: 200;
  };

export type patchWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdExercisesReorderResponseSuccess =
  patchWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdExercisesReorderResponse200 & {
    headers: Headers;
  };
export type patchWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdExercisesReorderResponse =
  patchWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdExercisesReorderResponseSuccess;

export const getPatchWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdExercisesReorderUrl =
  (workoutPlanId: string, workoutDayId: string) => {
    return `/workout-plans/${workoutPlanId}/days/${workoutDayId}/exercises/reorder`;
  };

export const patchWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdExercisesReorder =
  async (
    workoutPlanId: string,
    workoutDayId: string,
    patchWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdExercisesReorderBody: PatchWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdExercisesReorderBody,
    options?: RequestInit,
  ): Promise<patchWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdExercisesReorderResponse> => {
    return customFetch<patchWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdExercisesReorderResponse>(
      getPatchWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdExercisesReorderUrl(
        workoutPlanId,
        workoutDayId,
      ),
      {
        ...options,
        method: "PATCH",
        headers: { "Content-Type": "application/json", ...options?.headers },
        body: JSON.stringify(
          patchWorkoutPlansWorkoutPlanIdDaysWorkoutDayIdExercisesReorderBody,
        ),
      },
    );
  };

/**
 * @summary Chat with AI personal trainer
 */
export type postAiResponse200 = {
  data: void;
  status: 200;
};

export type postAiResponseSuccess = postAiResponse200 & {
  headers: Headers;
};
export type postAiResponse = postAiResponseSuccess;

export const getPostAiUrl = () => {
  return `/ai/`;
};

export const postAi = async (
  postAiBody: PostAiBody,
  options?: RequestInit,
): Promise<postAiResponse> => {
  return customFetch<postAiResponse>(getPostAiUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(postAiBody),
  });
};

/**
 * @summary Chat with AI sports nutrition assistant
 */
export type postNutritionAiResponse200 = {
  data: void;
  status: 200;
};

export type postNutritionAiResponseSuccess = postNutritionAiResponse200 & {
  headers: Headers;
};
export type postNutritionAiResponse = postNutritionAiResponseSuccess;

export const getPostNutritionAiUrl = () => {
  return `/nutrition/ai`;
};

export const postNutritionAi = async (
  postNutritionAiBody: PostNutritionAiBody,
  options?: RequestInit,
): Promise<postNutritionAiResponse> => {
  return customFetch<postNutritionAiResponse>(getPostNutritionAiUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(postNutritionAiBody),
  });
};

/**
 * @summary List nutrition plans
 */
export type listNutritionPlansResponse200 = {
  data: void;
  status: 200;
};

export type listNutritionPlansResponseSuccess =
  listNutritionPlansResponse200 & {
    headers: Headers;
  };
export type listNutritionPlansResponse = listNutritionPlansResponseSuccess;

export const getListNutritionPlansUrl = () => {
  return `/nutrition/plans`;
};

export const listNutritionPlans = async (
  options?: RequestInit,
): Promise<listNutritionPlansResponse> => {
  return customFetch<listNutritionPlansResponse>(getListNutritionPlansUrl(), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Get a nutrition plan
 */
export type getNutritionPlanResponse200 = {
  data: void;
  status: 200;
};

export type getNutritionPlanResponseSuccess = getNutritionPlanResponse200 & {
  headers: Headers;
};
export type getNutritionPlanResponse = getNutritionPlanResponseSuccess;

export const getGetNutritionPlanUrl = (id: string) => {
  return `/nutrition/plans/${id}`;
};

export const getNutritionPlan = async (
  id: string,
  options?: RequestInit,
): Promise<getNutritionPlanResponse> => {
  return customFetch<getNutritionPlanResponse>(getGetNutritionPlanUrl(id), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Delete a nutrition plan
 */
export type deleteNutritionPlanResponse200 = {
  data: void;
  status: 200;
};

export type deleteNutritionPlanResponseSuccess =
  deleteNutritionPlanResponse200 & {
    headers: Headers;
  };
export type deleteNutritionPlanResponse = deleteNutritionPlanResponseSuccess;

export const getDeleteNutritionPlanUrl = (id: string) => {
  return `/nutrition/plans/${id}`;
};

export const deleteNutritionPlan = async (
  id: string,
  options?: RequestInit,
): Promise<deleteNutritionPlanResponse> => {
  return customFetch<deleteNutritionPlanResponse>(
    getDeleteNutritionPlanUrl(id),
    {
      ...options,
      method: "DELETE",
    },
  );
};

/**
 * @summary Update a nutrition plan
 */
export type updateNutritionPlanResponse200 = {
  data: void;
  status: 200;
};

export type updateNutritionPlanResponseSuccess =
  updateNutritionPlanResponse200 & {
    headers: Headers;
  };
export type updateNutritionPlanResponse = updateNutritionPlanResponseSuccess;

export const getUpdateNutritionPlanUrl = (id: string) => {
  return `/nutrition/plans/${id}`;
};

export const updateNutritionPlan = async (
  id: string,
  options?: RequestInit,
): Promise<updateNutritionPlanResponse> => {
  return customFetch<updateNutritionPlanResponse>(
    getUpdateNutritionPlanUrl(id),
    {
      ...options,
      method: "PATCH",
    },
  );
};

/**
 * @summary Get a nutrition day
 */
export type getNutritionDayResponse200 = {
  data: void;
  status: 200;
};

export type getNutritionDayResponseSuccess = getNutritionDayResponse200 & {
  headers: Headers;
};
export type getNutritionDayResponse = getNutritionDayResponseSuccess;

export const getGetNutritionDayUrl = (id: string) => {
  return `/nutrition/days/${id}`;
};

export const getNutritionDay = async (
  id: string,
  options?: RequestInit,
): Promise<getNutritionDayResponse> => {
  return customFetch<getNutritionDayResponse>(getGetNutritionDayUrl(id), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary List exercises
 */
export type getExercisesResponse200 = {
  data: GetExercises200Item[];
  status: 200;
};

export type getExercisesResponseSuccess = getExercisesResponse200 & {
  headers: Headers;
};
export type getExercisesResponse = getExercisesResponseSuccess;

export const getGetExercisesUrl = (params?: GetExercisesParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/exercises?${stringifiedParams}`
    : `/exercises`;
};

export const getExercises = async (
  params?: GetExercisesParams,
  options?: RequestInit,
): Promise<getExercisesResponse> => {
  return customFetch<getExercisesResponse>(getGetExercisesUrl(params), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Get exercise by id
 */
export type getExercisesIdResponse200 = {
  data: GetExercisesId200;
  status: 200;
};

export type getExercisesIdResponse404 = {
  data: GetExercisesId404;
  status: 404;
};

export type getExercisesIdResponseSuccess = getExercisesIdResponse200 & {
  headers: Headers;
};
export type getExercisesIdResponseError = getExercisesIdResponse404 & {
  headers: Headers;
};

export type getExercisesIdResponse =
  | getExercisesIdResponseSuccess
  | getExercisesIdResponseError;

export const getGetExercisesIdUrl = (id: string) => {
  return `/exercises/${id}`;
};

export const getExercisesId = async (
  id: string,
  options?: RequestInit,
): Promise<getExercisesIdResponse> => {
  return customFetch<getExercisesIdResponse>(getGetExercisesIdUrl(id), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Become a trainer
 */
export type becomeTrainerResponse200 = {
  data: BecomeTrainer200;
  status: 200;
};

export type becomeTrainerResponse401 = {
  data: BecomeTrainer401;
  status: 401;
};

export type becomeTrainerResponse500 = {
  data: BecomeTrainer500;
  status: 500;
};

export type becomeTrainerResponseSuccess = becomeTrainerResponse200 & {
  headers: Headers;
};
export type becomeTrainerResponseError = (
  | becomeTrainerResponse401
  | becomeTrainerResponse500
) & {
  headers: Headers;
};

export type becomeTrainerResponse =
  | becomeTrainerResponseSuccess
  | becomeTrainerResponseError;

export const getBecomeTrainerUrl = () => {
  return `/trainer/become`;
};

export const becomeTrainer = async (
  becomeTrainerBody: BecomeTrainerBody,
  options?: RequestInit,
): Promise<becomeTrainerResponse> => {
  return customFetch<becomeTrainerResponse>(getBecomeTrainerUrl(), {
    ...options,
    method: "PATCH",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(becomeTrainerBody),
  });
};

/**
 * @summary Link a trainer by email
 */
export type linkTrainerResponse200 = {
  data: LinkTrainer200;
  status: 200;
};

export type linkTrainerResponse400 = {
  data: LinkTrainer400;
  status: 400;
};

export type linkTrainerResponse401 = {
  data: LinkTrainer401;
  status: 401;
};

export type linkTrainerResponse500 = {
  data: LinkTrainer500;
  status: 500;
};

export type linkTrainerResponseSuccess = linkTrainerResponse200 & {
  headers: Headers;
};
export type linkTrainerResponseError = (
  | linkTrainerResponse400
  | linkTrainerResponse401
  | linkTrainerResponse500
) & {
  headers: Headers;
};

export type linkTrainerResponse =
  | linkTrainerResponseSuccess
  | linkTrainerResponseError;

export const getLinkTrainerUrl = () => {
  return `/trainer/link`;
};

export const linkTrainer = async (
  linkTrainerBody: LinkTrainerBody,
  options?: RequestInit,
): Promise<linkTrainerResponse> => {
  return customFetch<linkTrainerResponse>(getLinkTrainerUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(linkTrainerBody),
  });
};

/**
 * @summary Get my students
 */
export type getMyStudentsResponse200 = {
  data: GetMyStudents200Item[];
  status: 200;
};

export type getMyStudentsResponse401 = {
  data: GetMyStudents401;
  status: 401;
};

export type getMyStudentsResponse500 = {
  data: GetMyStudents500;
  status: 500;
};

export type getMyStudentsResponseSuccess = getMyStudentsResponse200 & {
  headers: Headers;
};
export type getMyStudentsResponseError = (
  | getMyStudentsResponse401
  | getMyStudentsResponse500
) & {
  headers: Headers;
};

export type getMyStudentsResponse =
  | getMyStudentsResponseSuccess
  | getMyStudentsResponseError;

export const getGetMyStudentsUrl = () => {
  return `/trainer/students`;
};

export const getMyStudents = async (
  options?: RequestInit,
): Promise<getMyStudentsResponse> => {
  return customFetch<getMyStudentsResponse>(getGetMyStudentsUrl(), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Accept or reject a student
 */
export type respondStudentRequestResponse200 = {
  data: RespondStudentRequest200;
  status: 200;
};

export type respondStudentRequestResponse401 = {
  data: RespondStudentRequest401;
  status: 401;
};

export type respondStudentRequestResponse404 = {
  data: RespondStudentRequest404;
  status: 404;
};

export type respondStudentRequestResponse500 = {
  data: RespondStudentRequest500;
  status: 500;
};

export type respondStudentRequestResponseSuccess =
  respondStudentRequestResponse200 & {
    headers: Headers;
  };
export type respondStudentRequestResponseError = (
  | respondStudentRequestResponse401
  | respondStudentRequestResponse404
  | respondStudentRequestResponse500
) & {
  headers: Headers;
};

export type respondStudentRequestResponse =
  | respondStudentRequestResponseSuccess
  | respondStudentRequestResponseError;

export const getRespondStudentRequestUrl = (linkId: string) => {
  return `/trainer/students/${linkId}`;
};

export const respondStudentRequest = async (
  linkId: string,
  respondStudentRequestBody: RespondStudentRequestBody,
  options?: RequestInit,
): Promise<respondStudentRequestResponse> => {
  return customFetch<respondStudentRequestResponse>(
    getRespondStudentRequestUrl(linkId),
    {
      ...options,
      method: "PATCH",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(respondStudentRequestBody),
    },
  );
};

/**
 * @summary Get student workout plans
 */
export type getStudentPlansResponse200 = {
  data: unknown[];
  status: 200;
};

export type getStudentPlansResponse401 = {
  data: GetStudentPlans401;
  status: 401;
};

export type getStudentPlansResponse404 = {
  data: GetStudentPlans404;
  status: 404;
};

export type getStudentPlansResponse500 = {
  data: GetStudentPlans500;
  status: 500;
};

export type getStudentPlansResponseSuccess = getStudentPlansResponse200 & {
  headers: Headers;
};
export type getStudentPlansResponseError = (
  | getStudentPlansResponse401
  | getStudentPlansResponse404
  | getStudentPlansResponse500
) & {
  headers: Headers;
};

export type getStudentPlansResponse =
  | getStudentPlansResponseSuccess
  | getStudentPlansResponseError;

export const getGetStudentPlansUrl = (studentId: string) => {
  return `/trainer/students/${studentId}/plans`;
};

export const getStudentPlans = async (
  studentId: string,
  options?: RequestInit,
): Promise<getStudentPlansResponse> => {
  return customFetch<getStudentPlansResponse>(
    getGetStudentPlansUrl(studentId),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * Hello world
 */
export type getResponse200 = {
  data: Get200;
  status: 200;
};

export type getResponseSuccess = getResponse200 & {
  headers: Headers;
};
export type getResponse = getResponseSuccess;

export const getGetUrl = () => {
  return `/`;
};

export const get = async (options?: RequestInit): Promise<getResponse> => {
  return customFetch<getResponse>(getGetUrl(), {
    ...options,
    method: "GET",
  });
};
